apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-summarizer
  namespace: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-summarizer
  template:
    metadata:
      labels:
        app: llm-summarizer
    spec:
      containers:
      - name: summarizer
        image: llm-summarizer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10