apiVersion: v1
kind: Service
metadata:
  name: llm-summarizer-service
  namespace: llm
spec:
  selector:
    app: llm-summarizer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer